[package]
name = "bake-agent-context-tasks"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
socketry-project = "0.3"
bake = "0"
bake-agent-context = { version = "0.2.2", path = ".." }
bake-cargo = { version = "0.2.10" }
bake-license = { version = "0.1.6" }
bake-releases = { version = "0.2.4" }

[dev-dependencies]
tempfile = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage)"] }
